### ISSUE TITLE
Demo is currently broken

### ISSUE THREAD

**Issue by ryandrew14** [plotly/plotly-icons#41]
Thought I'd let you know your Zeit deployment (linked in readme) is not currently working:

<img width="694" alt="Screen Shot 2020-03-03 at 3 30 21 PM" src="https://user-images.githubusercontent.com/13836027/75829849-1cd42780-5d64-11ea-8d2b-cc0acf602493.png">

**Comment by nicolaskruchten** [comment]
Thanks! I "fixed" this by removing the link in the readme ;)
