### ISSUE TITLE
Can I use .svg files in my project?

### ISSUE THREAD

**Issue by aknorsh** [plotly/plotly-icons#43]
I'm currently using plotly.js in a commercial project that uses vue.js instead of react. but I'd like to use plotly-icons in my project.

Is it OK to pull the .svg files from this repo into the project?

Thanks.

**Comment by dmt0** [comment]
Hi @aknorsh, this repo is MIT licensed, just like plotly.js, so yes, you're welcome to use them in a commercial project!

**Comment by aknorsh** [comment]
I got it. Thank you for your reply!
